environments:
  sit:
    login_url: "https://cloudsit.cm253.com/control/login"
    username: "16673532843"
    password: "Li94122334@"
    control_url : "https://cloudsit.cm253.com/control/home"
    constant_template : "测试 www.baidu.com 测试"
    variable_template : "白模版测试【测试】{s}"
    constantsend_url : "https://cloudsit.cm253.com/control/sms/cl_market_sms/onlineSend"
    variablesend_url : "https://cloudsit.cm253.com/control/sms/cl_market_sms/variableSend"
    sendrecords_url : "https://cloudsit.cm253.com/control/sms/cl_market_sms/send-records"
  prod:
    login_url: "https://www.chuanglan.com/control/login"
    username: "15274438093"
    password: "Li94122334@"
    control_url: "https://www.chuanglan.com/control/home"
    constant_template : "测试 www.baidu.com 短信"
    variable_template : "白模版测试【测试】{s}"
    constantsend_url : "https://www.chuanglan.com/control/sms/cl_market_sms/onlineSend"
    variablesend_url : "https://www.chuanglan.com/control/sms/cl_market_sms/variableSend"
    sendrecords_url : "https://www.chuanglan.com/control/sms/cl_market_sms/send-records"