environments:
  sit:
    login_url: "https://cloudsit.cm253.com/control/login"
    username: "16673532843"
    password: "Li94122334@"
    control_url: "https://cloudsit.cm253.com/control/home"
    constant_template: "sit自动化常量模板"
    variable_template: "sit自动化变量模板{s}"
    constant_send_url: "https://cloudsit.cm253.com/control/sms/cl_market_sms/onlineSend"
    variable_send_url: "https://cloudsit.cm253.com/control/sms/cl_market_sms/variableSend"
    send_records_url: "https://cloudsit.cm253.com/control/sms/cl_market_sms/send-records"
    assert_constant_template: "【创蓝云智】sit自动化常量模板拒收请回复R"
    assert_variable_template: "【创蓝云智】sit自动化变量模板生产测试拒收请回复R"
    assert_report: "DELIVRD"
  prod:
    login_url: "https://www.chuanglan.com/control/login"
    username: "15274438093"
    password: "Li94122334@"
    control_url: "https://www.chuanglan.com/control/home"
    constant_template: "prod自动化常量模板"
    variable_template: "prod自动化变量模板{s}"
    constant_send_url: "https://www.chuanglan.com/control/sms/cl_market_sms/onlineSend"
    variable_send_url: "https://www.chuanglan.com/control/sms/cl_market_sms/variableSend"
    send_records_url: "https://www.chuanglan.com/control/sms/cl_market_sms/send-records"
    assert_constant_template: "【创蓝云智】prod自动化常量模板拒收请回复R"
    assert_variable_template: "【创蓝云智】prod自动化变量模板测试拒收请回复R"
    assert_report: "DELIVRD"